#Configuration File

#Combine Directory
$in=static/css&out=static/live/dir.css

#Combine Javascript
$in=static/js&out=static/live/all.js
  lib/a.js
  b.js
  c.js

#Combine CSS
$in=static/css&out=static/live/all.css
  site.css
  a.css
  b.css