#Configuration File

#Combine Directory, doesn't run combine at the first time
?in=static/css&out=static/live/dir.css&run=false

#Combine Javascript
?in=static/js&out=static/live/debug.js
  lib/a.js
  b.js
  c.js
#Minify the combined javascript
$java -jar tools/yuicompressor-2.4.7.jar static/live/debug.js -o static/live/debug.min.js

#Combine CSS, just combine at the first time, doens't watch change on it.
?in=static/css&out=static/live/debug.css&watch=0
#Minify the combined css
$java -jar tools/yuicompressor-2.4.7.jar static/live/debug.css -o static/live/debug.min.css
  site.css
  a.css
  b.css