#Configuration File

#Combine Directory, doesn't run combine at the first time
?in=static/css&out=static/live/dir.css&run=false

#Combine Javascript
?in=static/js&out=static/live/all.js&run=0
  lib/a.js
  b.js
  c.js

#Combine CSS, just combine at the first time, doens't watch change on it.
?in=static/css&out=static/live/all.css&watch=0&run=1
  site.css
  a.css
  b.css